language: python

python:
    - 2.7.6

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - pip install --use-mirrors tornado twisted pyyaml 

services:
  - rabbitmq
  - redis

script:
  - python fiware-pep8.py .
  - sudo ./build.sh

after_success:
  - coveralls